#!/bin/bash

# System Information
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

source /etc/os-release
OS="$PRETTY_NAME"

UPTIME=$(uptime -p)

CPU=$(lscpu | awk -F: '/Model name/ {gsub(/^[ \t]+/,"",$2); print $2}')

RAM=$(free -h | awk '/Mem:/ {print $2}')

DISKS=$(lsblk -d -o MODEL,SIZE | awk 'NR>1 {print $1" "$2}' | paste -sd ", ")

VIDEO=$(lspci 2>/dev/null | grep -i 'vga\|3d\|display' | cut -d: -f3- | sed 's/^ //')

HOSTADDRESS=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $7; exit}')

GATEWAY=$(ip route | awk '/default/ {print $3; exit}')

DNS=$(awk '/nameserver/ {print $2; exit}' /etc/resolv.conf)

# System Status
USERS=$(who | awk '{print $1}' | sort -u | paste -sd ",")

DISKSPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1" "$2}' | paste -sd ", ")

PROCESSCOUNT=$(ps -e --no-headers | wc -l)

LOADAVGERAGES=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')

PORTSAVAILABLE=$(ss -tulnH | awk '{print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd ",")

UFWSTATUS=$(sudo ufw status 2>/dev/null | head -1)

cat <<EOF

System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOSTADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISKSPACE
Process Count: $PROCESSCOUNT
Load Averages: $LOADAVERAGES
Listening Network Ports: $PORTSAVAILABLE
UFW Status: $UFWSTATUS

EOF
